# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               My Blogs
tagline:             'A set of technical notes'
description:         'Notes about technical books, papers. Learn and practice often.'
url:                 dongwang218.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Dong Wang
  url:               https://twitter.com/dongwang218

# Custom vars
version:             1.0.0
# Gems
plugins: [jekyll-paginate]
